name: CI Playground

on:
  push:
    branches: ["main"]

jobs:
  fitur-ci:
    runs-on: ubuntu-latest # Sudah digeser ke dalam (2 spasi dari fitur-ci)
    steps: # Sudah digeser ke dalam (2 spasi dari fitur-ci)
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Dependensi
        run: go mod download # Diganti dari 'uses' menjadi 'run'

      - name: Run Unit Test
        run: go test -v ./... # Diganti dari 'uses' menjadi 'run'
